version: '3'
services:
  redis:
    restart: always
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    # volumes:
    #   - ./data/redis:/data
  # mysql:
  #   image: bitnami/mysql:latest
  #   container_name: mysql
  #   ports:
  #     - 3306:3306
  #   # volumes:
  #   #   - ./data/db:/bitnami/mysql/data
  #   #   - ./logs/db:/opt/bitnami/mysql/logs
  #   environment:
  #     MYSQL_USER: dcard
  #     MYSQL_PASSWORD: DcardPass
  #     MYSQL_DATABASE: dcard
  #     MYSQL_ROOT_PASSWORD: DcardPass
